runtime: nodejs10

handlers:

- url: /
  static_files: dicoding-submission/index.html
  upload: dicoding-submission/index.html

- url: /index
  static_files: dicoding-submission/index.html
  upload: dicoding-submission/index.html

- url: /dicoding-submission
  static_dir: dicoding-submission